Repository pixielabs/cavy, pull requests merged in 2020-05, with the labels that each got.

#175 added an example to README
  README.md
Labels: documentation, ready

#176 Updating XCode version in CircleCI
  .circleci/config.yml
Labels: ready

#182 Add tests for `containsText`
  src/TestScope.js
  test/CavyTester/src/App.js
  test/CavyTester/src/scenarios/containsText.js
  test/CavyTester/src/scenarios/containsTextNumerical.js
  test/CavyTester/src/scenarios/exists.js
Labels: code review

#183 Improve error message for `containsText`
  src/TestScope.js
  test/CavyTester/src/App.js
  test/CavyTester/src/scenarios/containsTextUnwrapped.js
Labels: code review
